language: go

go:
  - 1.11.x
  - 1.12.x

branches:
  only:
    - master

sudo: false
dist: trusty

env:
  - CONSUL_VERSION=1.6.0

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf7e28bf6b96c8e81aec
    on_success: change
    on_failure: always
    on_start: never

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - curl -L "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip" | funzip > $HOME/bin/consul
  - chmod +x $HOME/bin/consul

script:
  - make build check test
