language: go

go:
  - 1.7.x
  - 1.8.x

branches:
  only:
    - master

sudo: false
dist: trusty

env:
  - CONSUL_VERSION=0.8.1

install:
  - mkdir -p $HOME/bin
  - export PATH="$HOME/bin:$PATH"
  - curl -L "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip" | funzip > $HOME/bin/consul
  - chmod +x $HOME/bin/consul

script:
  - make check
  - make test
  - make
